# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xrmcp < Formula
  desc "Go CLI for managing and running the xrMCP runtime server."
  homepage "https://github.com/xrmcp/cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "8e5135040e123dccbe4a70bbe057ed8b321ccae5d17438ad1e14b4636340cb8c"

      define_method(:install) do
        bin.install "xrmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "de81855054d36795aa291d06821147c2a08e1857e49178c08db8932de85a4a99"

      define_method(:install) do
        bin.install "xrmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_linux_amd64.tar.gz"
      sha256 "9434b75b44642d69a04053cb9065c52591255ac92222d628e47354d95e59a665"
      define_method(:install) do
        bin.install "xrmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_linux_arm64.tar.gz"
      sha256 "8ab15aa42e4c74c9fe83226557748b4801b151dfdb245a0c4392a3d05e1015ee"
      define_method(:install) do
        bin.install "xrmcp"
      end
    end
  end

  test do
    system "#{bin}/xrmcp", "--help"
  end
end
