# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xrmcp < Formula
  desc "Go CLI for managing and running the xrMCP runtime server."
  homepage "https://github.com/xrmcp/cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "6d4d493dd937c605e0e1811dc6cc34aa7cf314bb8fc70648e4a6e7ac0c1e1b8a"

      define_method(:install) do
        bin.install "xrmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "65c6aa5f6e8e40d7f815fe8a464a3c15f6ae2067a8fdca2303acda23eb0bc954"

      define_method(:install) do
        bin.install "xrmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_linux_amd64.tar.gz"
      sha256 "77276f9e3e09ac617fca5a4096675e5a2763ea2b3d16d9c818ea03c038d4e5b0"
      define_method(:install) do
        bin.install "xrmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.0/xrmcp_0.1.0_linux_arm64.tar.gz"
      sha256 "19f1633e17795bcea2c66a3669678f83cbf572fb308d1c2d19da1a9b1af4d889"
      define_method(:install) do
        bin.install "xrmcp"
      end
    end
  end

  test do
    system "#{bin}/xrmcp", "--help"
  end
end
