# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xrmcp < Formula
  desc "Go CLI for managing and running the xrMCP runtime server."
  homepage "https://github.com/xrmcp/cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.1/xrmcp_0.1.1_darwin_amd64.tar.gz"
      sha256 "03b6ca13ff175ab6ea734016da15de1b6b8f65a85b69ba4c7364b59b466505fb"

      define_method(:install) do
        bin.install "xrmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.1/xrmcp_0.1.1_darwin_arm64.tar.gz"
      sha256 "23519b027bd83e26c83514f2feada398340fd58fe200bba85e98b54ccc0e9ba0"

      define_method(:install) do
        bin.install "xrmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.1/xrmcp_0.1.1_linux_amd64.tar.gz"
      sha256 "4fee14854aa2512250abab75474dcfd9640f1b514deb35cff372c4b825319c49"
      define_method(:install) do
        bin.install "xrmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xrmcp/cli/releases/download/v0.1.1/xrmcp_0.1.1_linux_arm64.tar.gz"
      sha256 "47b1b6e3df07ec91706cb06184af4bc394e38c9ca7a9db6d8a470c07fa0bdb93"
      define_method(:install) do
        bin.install "xrmcp"
      end
    end
  end

  test do
    system "#{bin}/xrmcp", "--help"
  end
end
